x-common-networks: &common_networks
  networks:
    - airflow-network
 
##########################################################################################
################################    SERVICES CONFIG    ################################### 
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    ports:
      - 9090:9090
    volumes:
      - ../mnt/prometheus/conf/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-dev-data:/prometheus
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9090" ]
      interval: 30s
      timeout: 10s
      retries: 3
    <<: *common_networks
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
 
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    healthcheck:
      test: [ "CMD", "nc", "-z", "prometheus", "9090" ]
      interval: 30s
      timeout: 10s
      retries: 3
    <<: *common_networks
    volumes:
      - grafana_dev_vol:/var/lib/grafana
 
 
  ########################################################################################
  ###############################    DOCKER EXPORTER     #################################
 
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.44.1-test
    container_name: cadvisor
    <<: *common_networks
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    command:
      - '--enable_metrics=advtcp,app,cpu,cpuLoad,cpu_topology,disk,diskIO,memory,memory_numa,network'
    restart: unless-stopped
 
  ########################################################################################
  #######################    MONITORING LOCAL SERVER    ##################################
 
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    <<: *common_networks
    command:
      - '--path.rootfs=/host'
    pid: host
    volumes:
      - '/:/host:ro,rslave'
 
############################    END OF SERVICES CONFIG    ################################
##########################################################################################
 
volumes:
  prometheus-dev-data:
  grafana_dev_vol:
 
networks:
  airflow-network:
    name: airflow-network