version: '2'

services:
  spark:
    container_name: spark_master
    build: ../docker/spark_cluster
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8090:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - airflow-network

  spark-worker:
    build: ../docker/spark_cluster
    container_name: spark_worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - airflow-network

  spark_job:
    build: ../docker/spark_jobs
    container_name: spark_job
    volumes:
      - ../docker/spark_jobs/src:/app
    networks:
      - airflow-network
    environment:
      "bronze_path": ${BRONZE_PATH}
      "silver_path": ${SILVER_PATH}
      "gold_path": ${GOLD_PATH}
      "aws_access_key": ${AWS_ACCESS_KEY}
      "aws_secret_key": ${AWS_SECRET_KEY}

networks:
  airflow-network:
    name: airflow-network