global:
  scrape_interval: 50s
  scrape_timeout: 40s
 
scrape_configs:
 
  - job_name: prometheus
    static_configs:
      - targets:
        - prometheus:9090
 
  - job_name: node_exporter
    static_configs:
      - targets:
        - node_exporter:9100
  
  - job_name: cadvisor
    scrape_interval: 5s 
    static_configs: 
    - targets: ["cadvisor:8080"]